### PR TITLE
Include the name and options of schema units

### PR DESCRIPTION
**Pull request by mattcasey**
I need to know the name and list of options for the columns in a table. I didn't see any methods on the Page object itself to get properties, so I am using `collection.getSchemaUnits()`. let me know if there's something else I should use!

### CODE REVIEW

**Comment by Devorein** [comment]
@mattcasey just use `SchemaUnit.getCachedChildData()` to get the all the data for that specific schemaunit

**Comment by Devorein** [comment]
Unfortunately attaching name to the class is extremely problematic as I have to manually update the name property for all the objects created from that class if one updates the schemaunit name, and attaching options can not be done as its gonna work only for multi_select and select since other schemaunit type does not contain such properties.

**Comment by Devorein** [comment]
If you face any other problem let me know, for now, due to the above mentioned reasons I'm closing this PR

**Comment by mattcasey** [comment]
Thanks, `getCachedChildData()` worked fine for me!

**Comment by Devorein** [comment]
Awesome glad that solved the issue

**Pull request closed without merging**
